rootdir = 'C:\Users\Micha\OneDrive - bwstaff'; %'C:\Users\Micha\OneDrive - bwstaff
destdir = 'C:\Users\Micha\OneDrive - bwstaff\Export';

filedirs = {...
    '\MATLAB\toolboxes_own\heavy',...
    '\MATLAB\utility',...
    '\MATLAB\toolboxes_own\distributions',...
    '\MATLAB\toolboxes_downloaded\mhg15',...
    '\MATLAB\toolboxes_downloaded\MFE Finance Toolbox Kevin Sheppard\utility'...
    };

for ii = 1:length(filedirs)
    cpdir = strcat(rootdir,filedirs{ii});
    dest = strcat(destdir,filedirs{ii});
    mkdir(dest)
    copyfile(cpdir, dest)
end
