addpath(...
    genpath('C:\Users\m.stollenwerk\OneDrive - bwstaff\MATLAB\toolboxes_own\heavy'),...
    genpath('C:\Users\m.stollenwerk\OneDrive - bwstaff\MATLAB\toolboxes_own\utility'),...
    genpath('C:\Users\m.stollenwerk\OneDrive - bwstaff\MATLAB\toolboxes_own\distributions'),...
    genpath('C:\Users\m.stollenwerk\OneDrive - bwstaff\MATLAB\toolboxes_downloaded\mhg15'),...
    genpath('C:\Users\m.stollenwerk\OneDrive - bwstaff\MATLAB\toolboxes_downloaded\MFE Finance Toolbox Kevin Sheppard\utility')...
)

addpath(...
    genpath('C:\Users\Micha\OneDrive - bwstaff\MATLAB\toolboxes_own\heavy'),...
    genpath('C:\Users\Micha\OneDrive - bwstaff\MATLAB\toolboxes_own\utility'),...
    genpath('C:\Users\Micha\OneDrive - bwstaff\MATLAB\toolboxes_own\distributions'),...
    genpath('C:\Users\Micha\OneDrive - bwstaff\MATLAB\toolboxes_downloaded\mhg15'),...
    genpath('C:\Users\Micha\OneDrive - bwstaff\MATLAB\toolboxes_downloaded\MFE Finance Toolbox Kevin Sheppard\utility')...
)